const ADMIN_DB_TABLES = {
    companies: {
        label: "Companies",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    materials: {
        label: "Materials",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    thicknesses: {
        label: "Thicknesses",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    profiles: {
        label: "Profiles",
        primaryKey: ["id"],
        orderBy: "email",
        columns: {
            id: { type: "uuid", editable: false },
            email: { type: "text", required: true },
            full_name: { type: "text" },
            system_role: { type: "enum", required: true, options: ["super_admin", "manager", "status_user"] },
            company_id: { type: "bigint" },
            active: { type: "boolean", defaultValue: true },
            can_inventory_check: { type: "boolean", defaultValue: false },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    remnants: {
        label: "Remnants",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            company_id: { type: "bigint", required: true },
            material_id: { type: "bigint", required: true },
            thickness_id: { type: "bigint", required: true },
            name: { type: "text", required: true },
            width: { type: "numeric", required: true },
            height: { type: "numeric", required: true },
            l_shape: { type: "boolean", defaultValue: false },
            l_width: { type: "numeric" },
            l_height: { type: "numeric" },
            status: { type: "enum", required: true, options: ["available", "hold", "sold"], defaultValue: "available" },
            location: { type: "text" },
            hash: { type: "text" },
            image: { type: "text" },
            updated_at: { type: "timestamptz", editable: false },
            photo_hash: { type: "text" },
            image_path: { type: "text" },
            photo_synced_at: { type: "timestamptz" },
            source_image_url: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            deleted_at: { type: "timestamptz" },
            last_seen_at: { type: "timestamptz" },
            moraware_remnant_id: { type: "bigint" },
        },
    },
    holds: {
        label: "Holds",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            remnant_id: { type: "bigint", required: true },
            company_id: { type: "bigint", required: true },
            hold_owner_user_id: { type: "uuid", required: true },
            hold_started_at: { type: "timestamptz" },
            expires_at: { type: "timestamptz", required: true },
            status: { type: "enum", required: true, options: ["active", "expired", "released", "sold"] },
            notes: { type: "text" },
            job_number: { type: "text" },
            released_at: { type: "timestamptz" },
            released_by_user_id: { type: "uuid" },
            reassigned_from_user_id: { type: "uuid" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    hold_requests: {
        label: "Hold Requests",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            remnant_id: { type: "bigint", required: true },
            company_id: { type: "bigint" },
            requester_name: { type: "text", required: true },
            requester_email: { type: "text", required: true },
            sales_rep_user_id: { type: "uuid" },
            sales_rep_name: { type: "text" },
            notes: { type: "text" },
            job_number: { type: "text" },
            status: { type: "enum", required: true, options: ["pending", "approved", "rejected", "cancelled"], defaultValue: "pending" },
            reviewed_at: { type: "timestamptz" },
            reviewed_by_user_id: { type: "uuid" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    notification_queue: {
        label: "Notification Queue",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            notification_type: { type: "text", required: true },
            target_user_id: { type: "uuid" },
            target_email: { type: "text" },
            remnant_id: { type: "bigint" },
            hold_id: { type: "bigint" },
            hold_request_id: { type: "bigint" },
            payload: { type: "jsonb", defaultValue: {} },
            scheduled_for: { type: "timestamptz" },
            sent_at: { type: "timestamptz" },
            status: { type: "enum", required: true, options: ["pending", "sent", "failed", "cancelled"], defaultValue: "pending" },
            error: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    remnant_sales: {
        label: "Remnant Sales",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            remnant_id: { type: "bigint", required: true },
            company_id: { type: "bigint" },
            sold_by_user_id: { type: "uuid" },
            sold_at: { type: "timestamptz", required: true },
            notes: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
            job_number: { type: "text", required: true },
        },
    },
    audit_logs: {
        label: "Audit Logs",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            actor_user_id: { type: "uuid" },
            actor_email: { type: "text" },
            actor_role: { type: "text" },
            actor_company_id: { type: "bigint" },
            event_type: { type: "text", required: true },
            entity_type: { type: "text", required: true },
            entity_id: { type: "bigint" },
            remnant_id: { type: "bigint" },
            company_id: { type: "bigint" },
            message: { type: "text" },
            old_data: { type: "jsonb" },
            new_data: { type: "jsonb" },
            meta: { type: "jsonb" },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    suppliers: {
        label: "Suppliers",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            website_url: { type: "text" },
            inventory_url: { type: "text" },
            notes: { type: "text" },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    colors: {
        label: "Colors",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    finishes: {
        label: "Finishes",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            name: { type: "text", required: true },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    slabs: {
        label: "Slabs",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            material_id: { type: "bigint", required: true },
            name: { type: "text", required: true },
            width: { type: "text" },
            height: { type: "text" },
            color_tone: { type: "text" },
            detail_url: { type: "text", required: true },
            image_url: { type: "text" },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
            last_seen_at: { type: "timestamptz" },
            last_scrape_run_id: { type: "bigint" },
            deactivated_at: { type: "timestamptz" },
        },
    },
    stone_products: {
        label: "Stone Products",
        primaryKey: ["id"],
        orderBy: "display_name",
        columns: {
            id: { type: "bigint", editable: false },
            material_id: { type: "bigint", required: true },
            display_name: { type: "text", required: true },
            stone_name: { type: "text", required: true },
            brand_name: { type: "text" },
            normalized_name: { type: "text", editable: false },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    stone_product_colors: {
        label: "Stone Product Colors",
        primaryKey: ["stone_product_id", "color_id", "role"],
        orderBy: "stone_product_id",
        columns: {
            stone_product_id: { type: "bigint", required: true },
            color_id: { type: "bigint", required: true },
            role: { type: "enum", required: true, options: ["primary", "accent"], defaultValue: "primary" },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_price_tiers: {
        label: "Supplier Price Tiers",
        primaryKey: ["id"],
        orderBy: "sort_order",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            material_id: { type: "bigint" },
            code: { type: "text", required: true },
            sort_order: { type: "integer", required: true },
            base_price_per_sqft: { type: "numeric", required: true },
            min_price_per_sqft: { type: "numeric", required: true },
            max_price_per_sqft: { type: "numeric", required: true },
            fixed_fee_per_sqft: { type: "numeric", required: true },
            fee_percent_1: { type: "numeric", required: true },
            fee_percent_2: { type: "numeric", required: true },
            adjusted_price_per_sqft: { type: "numeric", editable: false },
            notes: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    slab_supplier_prices: {
        label: "Slab Supplier Prices",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            slab_id: { type: "bigint", required: true },
            material_id: { type: "bigint" },
            finish_id: { type: "bigint" },
            thickness_id: { type: "bigint" },
            tier_id: { type: "bigint", required: true },
            supplier_sku: { type: "text" },
            supplier_product_name: { type: "text", required: true },
            source_group_number: { type: "integer" },
            source_group_label: { type: "text" },
            source_status: { type: "text" },
            size_label: { type: "text" },
            list_price_per_sqft: { type: "numeric", required: true },
            price_source: { type: "text", required: true },
            effective_on: { type: "date" },
            active: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    slab_colors: {
        label: "Slab Colors",
        primaryKey: ["slab_id", "color_id", "role"],
        orderBy: "slab_id",
        columns: {
            slab_id: { type: "bigint", required: true },
            color_id: { type: "bigint", required: true },
            role: { type: "enum", required: true, options: ["primary", "accent"] },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    slab_finishes: {
        label: "Slab Finishes",
        primaryKey: ["slab_id", "finish_id"],
        orderBy: "slab_id",
        columns: {
            slab_id: { type: "bigint", required: true },
            finish_id: { type: "bigint", required: true },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    slab_thicknesses: {
        label: "Slab Thicknesses",
        primaryKey: ["slab_id", "thickness_id"],
        orderBy: "slab_id",
        columns: {
            slab_id: { type: "bigint", required: true },
            thickness_id: { type: "bigint", required: true },
            created_at: { type: "timestamptz", editable: false },
        },
    },
    slab_scrape_runs: {
        label: "Slab Scrape Runs",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            importer_key: { type: "text", required: true },
            source_path: { type: "text" },
            status: { type: "text", required: true },
            started_at: { type: "timestamptz", editable: false },
            completed_at: { type: "timestamptz" },
            seen_count: { type: "integer", required: true, defaultValue: 0 },
            inserted_count: { type: "integer", required: true, defaultValue: 0 },
            updated_count: { type: "integer", required: true, defaultValue: 0 },
            deactivated_count: { type: "integer", required: true, defaultValue: 0 },
            notes: { type: "jsonb", defaultValue: {} },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_brands: {
        label: "Supplier Brands",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            brand_name: { type: "text", required: true },
            material_id: { type: "bigint" },
            notes: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_contacts: {
        label: "Supplier Contacts",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            name: { type: "text", required: true },
            phone_office: { type: "text" },
            phone_mobile: { type: "text" },
            email: { type: "text" },
            is_primary: { type: "boolean", defaultValue: false },
            notes: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_locations: {
        label: "Supplier Locations",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            address_line_1: { type: "text" },
            city: { type: "text" },
            state: { type: "text" },
            postal_code: { type: "text" },
            hours: { type: "text" },
            appointment_notes: { type: "text" },
            is_primary: { type: "boolean", defaultValue: false },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_terms: {
        label: "Supplier Terms",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            sample_fee_text: { type: "text" },
            tax_text: { type: "text" },
            payment_terms: { type: "text" },
            credit_terms: { type: "text" },
            min_slab_purchase_text: { type: "text" },
            ordering_method: { type: "text" },
            notes: { type: "text" },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
    supplier_materials: {
        label: "Supplier Materials",
        primaryKey: ["id"],
        orderBy: "id",
        columns: {
            id: { type: "bigint", editable: false },
            supplier_id: { type: "bigint", required: true },
            material_id: { type: "bigint", required: true },
            available: { type: "boolean", defaultValue: true },
            created_at: { type: "timestamptz", editable: false },
            updated_at: { type: "timestamptz", editable: false },
        },
    },
};

function listAdminTables() {
    return Object.entries(ADMIN_DB_TABLES).map(([name, config]) => ({
        name,
        label: config.label,
        primaryKey: [...config.primaryKey],
        orderBy: config.orderBy,
        columns: Object.entries(config.columns).map(([columnName, columnConfig]) => ({
            name: columnName,
            type: columnConfig.type,
            required: columnConfig.required === true,
            editable: columnConfig.editable !== false,
            options: Array.isArray(columnConfig.options) ? [...columnConfig.options] : null,
            defaultValue: Object.prototype.hasOwnProperty.call(columnConfig, "defaultValue")
                ? columnConfig.defaultValue
                : null,
        })),
    }));
}

export function getAdminTableConfig(tableName) {
    return ADMIN_DB_TABLES[tableName] || null;
}

export { ADMIN_DB_TABLES, listAdminTables };
