create table if not exists public.slab_scrape_runs (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  importer_key text not null,
  source_path text,
  status text not null default 'running',
  started_at timestamptz not null default timezone('utc'::text, now()),
  completed_at timestamptz,
  seen_count integer not null default 0,
  inserted_count integer not null default 0,
  updated_count integer not null default 0,
  deactivated_count integer not null default 0,
  notes jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists slab_scrape_runs_supplier_started_idx
  on public.slab_scrape_runs (supplier_id, started_at desc);

alter table public.slabs
  add column if not exists last_seen_at timestamptz,
  add column if not exists last_scrape_run_id bigint references public.slab_scrape_runs(id) on delete set null,
  add column if not exists deactivated_at timestamptz;

create index if not exists slabs_supplier_last_seen_idx
  on public.slabs (supplier_id, last_seen_at desc nulls last);

create index if not exists slabs_supplier_active_idx
  on public.slabs (supplier_id, active);

update public.slabs
set
  last_seen_at = coalesce(last_seen_at, updated_at, created_at),
  deactivated_at = case
    when active = false and deactivated_at is null then coalesce(updated_at, created_at, timezone('utc'::text, now()))
    else deactivated_at
  end
where last_seen_at is null
   or (active = false and deactivated_at is null);
